/********************************************************************************
** Form generated from reading UI file 'keyboardwidget.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_KEYBOARDWIDGET_H
#define UI_KEYBOARDWIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>
#include "keypushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_KeyBoardWidget
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    KeyPushButton *keyBtn1_1;
    KeyPushButton *keyBtn1_2;
    KeyPushButton *keyBtn1_3;
    KeyPushButton *keyBtn1_4;
    KeyPushButton *keyBtn1_5;
    KeyPushButton *keyBtn1_6;
    KeyPushButton *keyBtn1_7;
    KeyPushButton *keyBtn1_8;
    KeyPushButton *keyBtn1_9;
    KeyPushButton *keyBtn1_10;
    KeyPushButton *keyBtn1_11;
    KeyPushButton *keyBtn1_12;
    KeyPushButton *keyBtn1_13;
    KeyPushButton *keyBtn1_14;
    KeyPushButton *keyBtn1_15;
    KeyPushButton *keyBtn1_16;
    KeyPushButton *keyBtn1_17;
    KeyPushButton *keyBtn1_18;
    KeyPushButton *keyBtn1_19;
    KeyPushButton *zimuShiftBtn;
    KeyPushButton *keyBtn1_20;
    KeyPushButton *keyBtn1_21;
    KeyPushButton *keyBtn1_22;
    KeyPushButton *keyBtn1_23;
    KeyPushButton *keyBtn1_24;
    KeyPushButton *keyBtn1_25;
    KeyPushButton *zimuDeleteBtn;
    KeyPushButton *keyBtn1_26;
    QWidget *page_2;
    KeyPushButton *keyBtn2_16;
    KeyPushButton *keyBtn2_12;
    KeyPushButton *keyBtn2_15;
    KeyPushButton *keyBtn2_19;
    KeyPushButton *keyBtn2_20;
    KeyPushButton *keyBtn2_18;
    KeyPushButton *keyBtn2_13;
    KeyPushButton *keyBtn2_17;
    KeyPushButton *keyBtn2_14;
    KeyPushButton *keyBtn2_11;
    KeyPushButton *keyBtn2_25;
    KeyPushButton *keyBtn2_21;
    KeyPushButton *keyBtn2_24;
    KeyPushButton *numDeleteBtn;
    KeyPushButton *keyBtn2_27;
    KeyPushButton *keyBtn2_22;
    KeyPushButton *keyBtn2_26;
    KeyPushButton *keyBtn2_23;
    KeyPushButton *numShiftBtn;
    KeyPushButton *keyBtn2_6;
    KeyPushButton *keyBtn2_7;
    KeyPushButton *keyBtn2_8;
    KeyPushButton *keyBtn2_9;
    KeyPushButton *keyBtn2_10;
    KeyPushButton *keyBtn2_5;
    KeyPushButton *keyBtn2_1;
    KeyPushButton *keyBtn2_3;
    KeyPushButton *keyBtn2_2;
    KeyPushButton *keyBtn2_4;
    QFrame *frame;
    KeyPushButton *changeWidgetBtn;
    KeyPushButton *douhaoBtn;
    KeyPushButton *dotBtn;
    KeyPushButton *baspBtn;
    KeyPushButton *hideBtn;

    void setupUi(QWidget *KeyBoardWidget)
    {
        if (KeyBoardWidget->objectName().isEmpty())
            KeyBoardWidget->setObjectName(QStringLiteral("KeyBoardWidget"));
        KeyBoardWidget->resize(800, 192);
        KeyBoardWidget->setFocusPolicy(Qt::NoFocus);
        KeyBoardWidget->setStyleSheet(QStringLiteral("background-color: rgb(246, 246, 246);"));
        stackedWidget = new QStackedWidget(KeyBoardWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 800, 191));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        keyBtn1_1 = new KeyPushButton(page);
        keyBtn1_1->setObjectName(QStringLiteral("keyBtn1_1"));
        keyBtn1_1->setGeometry(QRect(10, 10, 70, 36));
        keyBtn1_1->setMinimumSize(QSize(70, 36));
        keyBtn1_1->setFocusPolicy(Qt::NoFocus);
        keyBtn1_2 = new KeyPushButton(page);
        keyBtn1_2->setObjectName(QStringLiteral("keyBtn1_2"));
        keyBtn1_2->setGeometry(QRect(89, 10, 70, 36));
        keyBtn1_2->setMinimumSize(QSize(70, 36));
        keyBtn1_2->setFocusPolicy(Qt::NoFocus);
        keyBtn1_3 = new KeyPushButton(page);
        keyBtn1_3->setObjectName(QStringLiteral("keyBtn1_3"));
        keyBtn1_3->setGeometry(QRect(168, 10, 70, 36));
        keyBtn1_3->setMinimumSize(QSize(70, 36));
        keyBtn1_3->setFocusPolicy(Qt::NoFocus);
        keyBtn1_4 = new KeyPushButton(page);
        keyBtn1_4->setObjectName(QStringLiteral("keyBtn1_4"));
        keyBtn1_4->setGeometry(QRect(247, 10, 70, 36));
        keyBtn1_4->setMinimumSize(QSize(70, 36));
        keyBtn1_4->setFocusPolicy(Qt::NoFocus);
        keyBtn1_5 = new KeyPushButton(page);
        keyBtn1_5->setObjectName(QStringLiteral("keyBtn1_5"));
        keyBtn1_5->setGeometry(QRect(326, 10, 70, 36));
        keyBtn1_5->setMinimumSize(QSize(70, 36));
        keyBtn1_5->setFocusPolicy(Qt::NoFocus);
        keyBtn1_6 = new KeyPushButton(page);
        keyBtn1_6->setObjectName(QStringLiteral("keyBtn1_6"));
        keyBtn1_6->setGeometry(QRect(404, 10, 70, 36));
        keyBtn1_6->setMinimumSize(QSize(70, 36));
        keyBtn1_6->setFocusPolicy(Qt::NoFocus);
        keyBtn1_7 = new KeyPushButton(page);
        keyBtn1_7->setObjectName(QStringLiteral("keyBtn1_7"));
        keyBtn1_7->setGeometry(QRect(483, 10, 70, 36));
        keyBtn1_7->setMinimumSize(QSize(70, 36));
        keyBtn1_7->setFocusPolicy(Qt::NoFocus);
        keyBtn1_8 = new KeyPushButton(page);
        keyBtn1_8->setObjectName(QStringLiteral("keyBtn1_8"));
        keyBtn1_8->setGeometry(QRect(562, 10, 70, 36));
        keyBtn1_8->setMinimumSize(QSize(70, 36));
        keyBtn1_8->setFocusPolicy(Qt::NoFocus);
        keyBtn1_9 = new KeyPushButton(page);
        keyBtn1_9->setObjectName(QStringLiteral("keyBtn1_9"));
        keyBtn1_9->setGeometry(QRect(641, 10, 70, 36));
        keyBtn1_9->setMinimumSize(QSize(70, 36));
        keyBtn1_9->setFocusPolicy(Qt::NoFocus);
        keyBtn1_10 = new KeyPushButton(page);
        keyBtn1_10->setObjectName(QStringLiteral("keyBtn1_10"));
        keyBtn1_10->setGeometry(QRect(720, 10, 70, 36));
        keyBtn1_10->setMinimumSize(QSize(70, 36));
        keyBtn1_10->setFocusPolicy(Qt::NoFocus);
        keyBtn1_11 = new KeyPushButton(page);
        keyBtn1_11->setObjectName(QStringLiteral("keyBtn1_11"));
        keyBtn1_11->setGeometry(QRect(51, 56, 70, 36));
        keyBtn1_11->setMinimumSize(QSize(70, 36));
        keyBtn1_11->setFocusPolicy(Qt::NoFocus);
        keyBtn1_12 = new KeyPushButton(page);
        keyBtn1_12->setObjectName(QStringLiteral("keyBtn1_12"));
        keyBtn1_12->setGeometry(QRect(129, 56, 70, 36));
        keyBtn1_12->setMinimumSize(QSize(70, 36));
        keyBtn1_12->setFocusPolicy(Qt::NoFocus);
        keyBtn1_13 = new KeyPushButton(page);
        keyBtn1_13->setObjectName(QStringLiteral("keyBtn1_13"));
        keyBtn1_13->setGeometry(QRect(207, 56, 70, 36));
        keyBtn1_13->setMinimumSize(QSize(70, 36));
        keyBtn1_13->setFocusPolicy(Qt::NoFocus);
        keyBtn1_14 = new KeyPushButton(page);
        keyBtn1_14->setObjectName(QStringLiteral("keyBtn1_14"));
        keyBtn1_14->setGeometry(QRect(285, 56, 70, 36));
        keyBtn1_14->setMinimumSize(QSize(70, 36));
        keyBtn1_14->setFocusPolicy(Qt::NoFocus);
        keyBtn1_15 = new KeyPushButton(page);
        keyBtn1_15->setObjectName(QStringLiteral("keyBtn1_15"));
        keyBtn1_15->setGeometry(QRect(363, 56, 70, 36));
        keyBtn1_15->setMinimumSize(QSize(70, 36));
        keyBtn1_15->setFocusPolicy(Qt::NoFocus);
        keyBtn1_16 = new KeyPushButton(page);
        keyBtn1_16->setObjectName(QStringLiteral("keyBtn1_16"));
        keyBtn1_16->setGeometry(QRect(441, 56, 70, 36));
        keyBtn1_16->setMinimumSize(QSize(70, 36));
        keyBtn1_16->setFocusPolicy(Qt::NoFocus);
        keyBtn1_17 = new KeyPushButton(page);
        keyBtn1_17->setObjectName(QStringLiteral("keyBtn1_17"));
        keyBtn1_17->setGeometry(QRect(519, 56, 70, 36));
        keyBtn1_17->setMinimumSize(QSize(70, 36));
        keyBtn1_17->setFocusPolicy(Qt::NoFocus);
        keyBtn1_18 = new KeyPushButton(page);
        keyBtn1_18->setObjectName(QStringLiteral("keyBtn1_18"));
        keyBtn1_18->setGeometry(QRect(597, 56, 70, 36));
        keyBtn1_18->setMinimumSize(QSize(70, 36));
        keyBtn1_18->setFocusPolicy(Qt::NoFocus);
        keyBtn1_19 = new KeyPushButton(page);
        keyBtn1_19->setObjectName(QStringLiteral("keyBtn1_19"));
        keyBtn1_19->setGeometry(QRect(675, 56, 70, 36));
        keyBtn1_19->setMinimumSize(QSize(70, 36));
        keyBtn1_19->setFocusPolicy(Qt::NoFocus);
        zimuShiftBtn = new KeyPushButton(page);
        zimuShiftBtn->setObjectName(QStringLiteral("zimuShiftBtn"));
        zimuShiftBtn->setGeometry(QRect(10, 102, 111, 36));
        zimuShiftBtn->setMinimumSize(QSize(70, 36));
        zimuShiftBtn->setFocusPolicy(Qt::NoFocus);
        keyBtn1_20 = new KeyPushButton(page);
        keyBtn1_20->setObjectName(QStringLiteral("keyBtn1_20"));
        keyBtn1_20->setGeometry(QRect(129, 102, 70, 36));
        keyBtn1_20->setMinimumSize(QSize(70, 36));
        keyBtn1_20->setFocusPolicy(Qt::NoFocus);
        keyBtn1_21 = new KeyPushButton(page);
        keyBtn1_21->setObjectName(QStringLiteral("keyBtn1_21"));
        keyBtn1_21->setGeometry(QRect(207, 102, 70, 36));
        keyBtn1_21->setMinimumSize(QSize(70, 36));
        keyBtn1_21->setFocusPolicy(Qt::NoFocus);
        keyBtn1_22 = new KeyPushButton(page);
        keyBtn1_22->setObjectName(QStringLiteral("keyBtn1_22"));
        keyBtn1_22->setGeometry(QRect(285, 102, 70, 36));
        keyBtn1_22->setMinimumSize(QSize(70, 36));
        keyBtn1_22->setFocusPolicy(Qt::NoFocus);
        keyBtn1_23 = new KeyPushButton(page);
        keyBtn1_23->setObjectName(QStringLiteral("keyBtn1_23"));
        keyBtn1_23->setGeometry(QRect(363, 102, 70, 36));
        keyBtn1_23->setMinimumSize(QSize(70, 36));
        keyBtn1_23->setFocusPolicy(Qt::NoFocus);
        keyBtn1_24 = new KeyPushButton(page);
        keyBtn1_24->setObjectName(QStringLiteral("keyBtn1_24"));
        keyBtn1_24->setGeometry(QRect(441, 102, 70, 36));
        keyBtn1_24->setMinimumSize(QSize(70, 36));
        keyBtn1_24->setFocusPolicy(Qt::NoFocus);
        keyBtn1_25 = new KeyPushButton(page);
        keyBtn1_25->setObjectName(QStringLiteral("keyBtn1_25"));
        keyBtn1_25->setGeometry(QRect(519, 102, 70, 36));
        keyBtn1_25->setMinimumSize(QSize(70, 36));
        keyBtn1_25->setFocusPolicy(Qt::NoFocus);
        zimuDeleteBtn = new KeyPushButton(page);
        zimuDeleteBtn->setObjectName(QStringLiteral("zimuDeleteBtn"));
        zimuDeleteBtn->setGeometry(QRect(675, 102, 116, 36));
        zimuDeleteBtn->setMinimumSize(QSize(70, 36));
        zimuDeleteBtn->setFocusPolicy(Qt::NoFocus);
        zimuDeleteBtn->setStyleSheet(QStringLiteral(""));
        keyBtn1_26 = new KeyPushButton(page);
        keyBtn1_26->setObjectName(QStringLiteral("keyBtn1_26"));
        keyBtn1_26->setGeometry(QRect(597, 102, 70, 36));
        keyBtn1_26->setMinimumSize(QSize(70, 36));
        keyBtn1_26->setFocusPolicy(Qt::NoFocus);
        stackedWidget->addWidget(page);
        zimuShiftBtn->raise();
        keyBtn1_20->raise();
        keyBtn1_21->raise();
        keyBtn1_22->raise();
        keyBtn1_23->raise();
        keyBtn1_24->raise();
        keyBtn1_25->raise();
        zimuDeleteBtn->raise();
        keyBtn1_26->raise();
        keyBtn1_1->raise();
        keyBtn1_2->raise();
        keyBtn1_3->raise();
        keyBtn1_4->raise();
        keyBtn1_5->raise();
        keyBtn1_6->raise();
        keyBtn1_7->raise();
        keyBtn1_8->raise();
        keyBtn1_9->raise();
        keyBtn1_10->raise();
        keyBtn1_11->raise();
        keyBtn1_12->raise();
        keyBtn1_13->raise();
        keyBtn1_14->raise();
        keyBtn1_15->raise();
        keyBtn1_16->raise();
        keyBtn1_17->raise();
        keyBtn1_18->raise();
        keyBtn1_19->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        keyBtn2_16 = new KeyPushButton(page_2);
        keyBtn2_16->setObjectName(QStringLiteral("keyBtn2_16"));
        keyBtn2_16->setGeometry(QRect(404, 56, 70, 36));
        keyBtn2_16->setMinimumSize(QSize(70, 36));
        keyBtn2_16->setFocusPolicy(Qt::NoFocus);
        keyBtn2_12 = new KeyPushButton(page_2);
        keyBtn2_12->setObjectName(QStringLiteral("keyBtn2_12"));
        keyBtn2_12->setGeometry(QRect(89, 56, 70, 36));
        keyBtn2_12->setMinimumSize(QSize(70, 36));
        keyBtn2_12->setFocusPolicy(Qt::NoFocus);
        keyBtn2_15 = new KeyPushButton(page_2);
        keyBtn2_15->setObjectName(QStringLiteral("keyBtn2_15"));
        keyBtn2_15->setGeometry(QRect(326, 56, 70, 36));
        keyBtn2_15->setMinimumSize(QSize(70, 36));
        keyBtn2_15->setFocusPolicy(Qt::NoFocus);
        keyBtn2_19 = new KeyPushButton(page_2);
        keyBtn2_19->setObjectName(QStringLiteral("keyBtn2_19"));
        keyBtn2_19->setGeometry(QRect(641, 56, 70, 36));
        keyBtn2_19->setMinimumSize(QSize(70, 36));
        keyBtn2_19->setFocusPolicy(Qt::NoFocus);
        keyBtn2_20 = new KeyPushButton(page_2);
        keyBtn2_20->setObjectName(QStringLiteral("keyBtn2_20"));
        keyBtn2_20->setGeometry(QRect(720, 56, 70, 36));
        keyBtn2_20->setMinimumSize(QSize(70, 36));
        keyBtn2_20->setFocusPolicy(Qt::NoFocus);
        keyBtn2_18 = new KeyPushButton(page_2);
        keyBtn2_18->setObjectName(QStringLiteral("keyBtn2_18"));
        keyBtn2_18->setGeometry(QRect(562, 56, 70, 36));
        keyBtn2_18->setMinimumSize(QSize(70, 36));
        keyBtn2_18->setFocusPolicy(Qt::NoFocus);
        keyBtn2_13 = new KeyPushButton(page_2);
        keyBtn2_13->setObjectName(QStringLiteral("keyBtn2_13"));
        keyBtn2_13->setGeometry(QRect(168, 56, 70, 36));
        keyBtn2_13->setMinimumSize(QSize(70, 36));
        keyBtn2_13->setFocusPolicy(Qt::NoFocus);
        keyBtn2_17 = new KeyPushButton(page_2);
        keyBtn2_17->setObjectName(QStringLiteral("keyBtn2_17"));
        keyBtn2_17->setGeometry(QRect(483, 56, 70, 36));
        keyBtn2_17->setMinimumSize(QSize(70, 36));
        keyBtn2_17->setFocusPolicy(Qt::NoFocus);
        keyBtn2_14 = new KeyPushButton(page_2);
        keyBtn2_14->setObjectName(QStringLiteral("keyBtn2_14"));
        keyBtn2_14->setGeometry(QRect(247, 56, 70, 36));
        keyBtn2_14->setMinimumSize(QSize(70, 36));
        keyBtn2_14->setFocusPolicy(Qt::NoFocus);
        keyBtn2_11 = new KeyPushButton(page_2);
        keyBtn2_11->setObjectName(QStringLiteral("keyBtn2_11"));
        keyBtn2_11->setGeometry(QRect(10, 56, 70, 36));
        keyBtn2_11->setMinimumSize(QSize(70, 36));
        keyBtn2_11->setFocusPolicy(Qt::NoFocus);
        keyBtn2_25 = new KeyPushButton(page_2);
        keyBtn2_25->setObjectName(QStringLiteral("keyBtn2_25"));
        keyBtn2_25->setGeometry(QRect(441, 102, 70, 36));
        keyBtn2_25->setMinimumSize(QSize(70, 36));
        keyBtn2_25->setFocusPolicy(Qt::NoFocus);
        keyBtn2_21 = new KeyPushButton(page_2);
        keyBtn2_21->setObjectName(QStringLiteral("keyBtn2_21"));
        keyBtn2_21->setGeometry(QRect(129, 102, 70, 36));
        keyBtn2_21->setMinimumSize(QSize(70, 36));
        keyBtn2_21->setFocusPolicy(Qt::NoFocus);
        keyBtn2_24 = new KeyPushButton(page_2);
        keyBtn2_24->setObjectName(QStringLiteral("keyBtn2_24"));
        keyBtn2_24->setGeometry(QRect(363, 102, 70, 36));
        keyBtn2_24->setMinimumSize(QSize(70, 36));
        keyBtn2_24->setFocusPolicy(Qt::NoFocus);
        numDeleteBtn = new KeyPushButton(page_2);
        numDeleteBtn->setObjectName(QStringLiteral("numDeleteBtn"));
        numDeleteBtn->setGeometry(QRect(675, 102, 116, 36));
        numDeleteBtn->setMinimumSize(QSize(70, 36));
        numDeleteBtn->setFocusPolicy(Qt::NoFocus);
        keyBtn2_27 = new KeyPushButton(page_2);
        keyBtn2_27->setObjectName(QStringLiteral("keyBtn2_27"));
        keyBtn2_27->setGeometry(QRect(597, 102, 70, 36));
        keyBtn2_27->setMinimumSize(QSize(70, 36));
        keyBtn2_27->setFocusPolicy(Qt::NoFocus);
        keyBtn2_22 = new KeyPushButton(page_2);
        keyBtn2_22->setObjectName(QStringLiteral("keyBtn2_22"));
        keyBtn2_22->setGeometry(QRect(207, 102, 70, 36));
        keyBtn2_22->setMinimumSize(QSize(70, 36));
        keyBtn2_22->setFocusPolicy(Qt::NoFocus);
        keyBtn2_26 = new KeyPushButton(page_2);
        keyBtn2_26->setObjectName(QStringLiteral("keyBtn2_26"));
        keyBtn2_26->setGeometry(QRect(519, 102, 70, 36));
        keyBtn2_26->setMinimumSize(QSize(70, 36));
        keyBtn2_26->setFocusPolicy(Qt::NoFocus);
        keyBtn2_23 = new KeyPushButton(page_2);
        keyBtn2_23->setObjectName(QStringLiteral("keyBtn2_23"));
        keyBtn2_23->setGeometry(QRect(285, 102, 70, 36));
        keyBtn2_23->setMinimumSize(QSize(70, 36));
        keyBtn2_23->setFocusPolicy(Qt::NoFocus);
        numShiftBtn = new KeyPushButton(page_2);
        numShiftBtn->setObjectName(QStringLiteral("numShiftBtn"));
        numShiftBtn->setGeometry(QRect(10, 102, 111, 36));
        numShiftBtn->setMinimumSize(QSize(70, 36));
        numShiftBtn->setFocusPolicy(Qt::NoFocus);
        keyBtn2_6 = new KeyPushButton(page_2);
        keyBtn2_6->setObjectName(QStringLiteral("keyBtn2_6"));
        keyBtn2_6->setGeometry(QRect(404, 10, 70, 36));
        keyBtn2_6->setMinimumSize(QSize(70, 36));
        keyBtn2_6->setFocusPolicy(Qt::NoFocus);
        keyBtn2_7 = new KeyPushButton(page_2);
        keyBtn2_7->setObjectName(QStringLiteral("keyBtn2_7"));
        keyBtn2_7->setGeometry(QRect(483, 10, 70, 36));
        keyBtn2_7->setMinimumSize(QSize(70, 36));
        keyBtn2_7->setFocusPolicy(Qt::NoFocus);
        keyBtn2_8 = new KeyPushButton(page_2);
        keyBtn2_8->setObjectName(QStringLiteral("keyBtn2_8"));
        keyBtn2_8->setGeometry(QRect(562, 10, 70, 36));
        keyBtn2_8->setMinimumSize(QSize(70, 36));
        keyBtn2_8->setFocusPolicy(Qt::NoFocus);
        keyBtn2_9 = new KeyPushButton(page_2);
        keyBtn2_9->setObjectName(QStringLiteral("keyBtn2_9"));
        keyBtn2_9->setGeometry(QRect(641, 10, 70, 36));
        keyBtn2_9->setMinimumSize(QSize(70, 36));
        keyBtn2_9->setFocusPolicy(Qt::NoFocus);
        keyBtn2_10 = new KeyPushButton(page_2);
        keyBtn2_10->setObjectName(QStringLiteral("keyBtn2_10"));
        keyBtn2_10->setGeometry(QRect(720, 10, 70, 36));
        keyBtn2_10->setMinimumSize(QSize(70, 36));
        keyBtn2_10->setFocusPolicy(Qt::NoFocus);
        keyBtn2_5 = new KeyPushButton(page_2);
        keyBtn2_5->setObjectName(QStringLiteral("keyBtn2_5"));
        keyBtn2_5->setGeometry(QRect(326, 10, 70, 36));
        keyBtn2_5->setMinimumSize(QSize(70, 36));
        keyBtn2_5->setFocusPolicy(Qt::NoFocus);
        keyBtn2_1 = new KeyPushButton(page_2);
        keyBtn2_1->setObjectName(QStringLiteral("keyBtn2_1"));
        keyBtn2_1->setGeometry(QRect(10, 10, 70, 36));
        keyBtn2_1->setMinimumSize(QSize(70, 36));
        keyBtn2_1->setFocusPolicy(Qt::NoFocus);
        keyBtn2_3 = new KeyPushButton(page_2);
        keyBtn2_3->setObjectName(QStringLiteral("keyBtn2_3"));
        keyBtn2_3->setGeometry(QRect(168, 10, 70, 36));
        keyBtn2_3->setMinimumSize(QSize(70, 36));
        keyBtn2_3->setFocusPolicy(Qt::NoFocus);
        keyBtn2_2 = new KeyPushButton(page_2);
        keyBtn2_2->setObjectName(QStringLiteral("keyBtn2_2"));
        keyBtn2_2->setGeometry(QRect(89, 10, 70, 36));
        keyBtn2_2->setMinimumSize(QSize(70, 36));
        keyBtn2_2->setFocusPolicy(Qt::NoFocus);
        keyBtn2_4 = new KeyPushButton(page_2);
        keyBtn2_4->setObjectName(QStringLiteral("keyBtn2_4"));
        keyBtn2_4->setGeometry(QRect(247, 10, 70, 36));
        keyBtn2_4->setMinimumSize(QSize(70, 36));
        keyBtn2_4->setFocusPolicy(Qt::NoFocus);
        stackedWidget->addWidget(page_2);
        frame = new QFrame(KeyBoardWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(0, 149, 800, 51));
        frame->setFrameShape(QFrame::NoFrame);
        frame->setFrameShadow(QFrame::Raised);
        changeWidgetBtn = new KeyPushButton(frame);
        changeWidgetBtn->setObjectName(QStringLiteral("changeWidgetBtn"));
        changeWidgetBtn->setGeometry(QRect(10, 0, 111, 36));
        changeWidgetBtn->setMinimumSize(QSize(70, 36));
        changeWidgetBtn->setFocusPolicy(Qt::NoFocus);
        douhaoBtn = new KeyPushButton(frame);
        douhaoBtn->setObjectName(QStringLiteral("douhaoBtn"));
        douhaoBtn->setGeometry(QRect(129, 0, 70, 36));
        douhaoBtn->setMinimumSize(QSize(70, 36));
        douhaoBtn->setFocusPolicy(Qt::NoFocus);
        dotBtn = new KeyPushButton(frame);
        dotBtn->setObjectName(QStringLiteral("dotBtn"));
        dotBtn->setGeometry(QRect(597, 0, 70, 36));
        dotBtn->setMinimumSize(QSize(70, 36));
        dotBtn->setFocusPolicy(Qt::NoFocus);
        baspBtn = new KeyPushButton(frame);
        baspBtn->setObjectName(QStringLiteral("baspBtn"));
        baspBtn->setGeometry(QRect(207, 0, 382, 36));
        baspBtn->setMinimumSize(QSize(300, 36));
        baspBtn->setFocusPolicy(Qt::NoFocus);
        hideBtn = new KeyPushButton(frame);
        hideBtn->setObjectName(QStringLiteral("hideBtn"));
        hideBtn->setGeometry(QRect(675, 0, 116, 36));
        hideBtn->setMinimumSize(QSize(70, 36));
        hideBtn->setFocusPolicy(Qt::NoFocus);
        hideBtn->setStyleSheet(QStringLiteral(""));

        retranslateUi(KeyBoardWidget);

        stackedWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(KeyBoardWidget);
    } // setupUi

    void retranslateUi(QWidget *KeyBoardWidget)
    {
        KeyBoardWidget->setWindowTitle(QApplication::translate("KeyBoardWidget", "Widget", 0));
        keyBtn1_1->setText(QApplication::translate("KeyBoardWidget", "q", 0));
        keyBtn1_2->setText(QApplication::translate("KeyBoardWidget", "w", 0));
        keyBtn1_3->setText(QApplication::translate("KeyBoardWidget", "e", 0));
        keyBtn1_4->setText(QApplication::translate("KeyBoardWidget", "r", 0));
        keyBtn1_5->setText(QApplication::translate("KeyBoardWidget", "t", 0));
        keyBtn1_6->setText(QApplication::translate("KeyBoardWidget", "y", 0));
        keyBtn1_7->setText(QApplication::translate("KeyBoardWidget", "u", 0));
        keyBtn1_8->setText(QApplication::translate("KeyBoardWidget", "i", 0));
        keyBtn1_9->setText(QApplication::translate("KeyBoardWidget", "o", 0));
        keyBtn1_10->setText(QApplication::translate("KeyBoardWidget", "p", 0));
        keyBtn1_11->setText(QApplication::translate("KeyBoardWidget", "a", 0));
        keyBtn1_12->setText(QApplication::translate("KeyBoardWidget", "s", 0));
        keyBtn1_13->setText(QApplication::translate("KeyBoardWidget", "d", 0));
        keyBtn1_14->setText(QApplication::translate("KeyBoardWidget", "f", 0));
        keyBtn1_15->setText(QApplication::translate("KeyBoardWidget", "g", 0));
        keyBtn1_16->setText(QApplication::translate("KeyBoardWidget", "h", 0));
        keyBtn1_17->setText(QApplication::translate("KeyBoardWidget", "j", 0));
        keyBtn1_18->setText(QApplication::translate("KeyBoardWidget", "k", 0));
        keyBtn1_19->setText(QApplication::translate("KeyBoardWidget", "l", 0));
        zimuShiftBtn->setText(QString());
        keyBtn1_20->setText(QApplication::translate("KeyBoardWidget", "z", 0));
        keyBtn1_21->setText(QApplication::translate("KeyBoardWidget", "x", 0));
        keyBtn1_22->setText(QApplication::translate("KeyBoardWidget", "c", 0));
        keyBtn1_23->setText(QApplication::translate("KeyBoardWidget", "v", 0));
        keyBtn1_24->setText(QApplication::translate("KeyBoardWidget", "b", 0));
        keyBtn1_25->setText(QApplication::translate("KeyBoardWidget", "n", 0));
        zimuDeleteBtn->setText(QApplication::translate("KeyBoardWidget", "\342\206\220", 0));
        keyBtn1_26->setText(QApplication::translate("KeyBoardWidget", "m", 0));
        keyBtn2_16->setText(QApplication::translate("KeyBoardWidget", ")", 0));
        keyBtn2_12->setText(QApplication::translate("KeyBoardWidget", "#", 0));
        keyBtn2_15->setText(QApplication::translate("KeyBoardWidget", "(", 0));
        keyBtn2_19->setText(QApplication::translate("KeyBoardWidget", "_", 0));
        keyBtn2_20->setText(QApplication::translate("KeyBoardWidget", "+", 0));
        keyBtn2_18->setText(QApplication::translate("KeyBoardWidget", "=", 0));
        keyBtn2_13->setText(QApplication::translate("KeyBoardWidget", "$", 0));
        keyBtn2_17->setText(QApplication::translate("KeyBoardWidget", "-", 0));
        keyBtn2_14->setText(QApplication::translate("KeyBoardWidget", "%", 0));
        keyBtn2_11->setText(QApplication::translate("KeyBoardWidget", "@", 0));
        keyBtn2_25->setText(QApplication::translate("KeyBoardWidget", "/", 0));
        keyBtn2_21->setText(QApplication::translate("KeyBoardWidget", "!", 0));
        keyBtn2_24->setText(QApplication::translate("KeyBoardWidget", "\"", 0));
        numDeleteBtn->setText(QApplication::translate("KeyBoardWidget", "\342\206\220", 0));
        keyBtn2_27->setText(QApplication::translate("KeyBoardWidget", ">", 0));
        keyBtn2_22->setText(QApplication::translate("KeyBoardWidget", ";", 0));
        keyBtn2_26->setText(QApplication::translate("KeyBoardWidget", "<", 0));
        keyBtn2_23->setText(QApplication::translate("KeyBoardWidget", ":", 0));
        numShiftBtn->setText(QString());
        keyBtn2_6->setText(QApplication::translate("KeyBoardWidget", "6", 0));
        keyBtn2_7->setText(QApplication::translate("KeyBoardWidget", "7", 0));
        keyBtn2_8->setText(QApplication::translate("KeyBoardWidget", "8", 0));
        keyBtn2_9->setText(QApplication::translate("KeyBoardWidget", "9", 0));
        keyBtn2_10->setText(QApplication::translate("KeyBoardWidget", "0", 0));
        keyBtn2_5->setText(QApplication::translate("KeyBoardWidget", "5", 0));
        keyBtn2_1->setText(QApplication::translate("KeyBoardWidget", "1", 0));
        keyBtn2_3->setText(QApplication::translate("KeyBoardWidget", "3", 0));
        keyBtn2_2->setText(QApplication::translate("KeyBoardWidget", "2", 0));
        keyBtn2_4->setText(QApplication::translate("KeyBoardWidget", "4", 0));
        changeWidgetBtn->setText(QApplication::translate("KeyBoardWidget", "&&123", 0));
        douhaoBtn->setText(QApplication::translate("KeyBoardWidget", ",", 0));
        dotBtn->setText(QApplication::translate("KeyBoardWidget", ".", 0));
        baspBtn->setText(QApplication::translate("KeyBoardWidget", "English", 0));
        hideBtn->setText(QApplication::translate("KeyBoardWidget", "\342\206\223", 0));
    } // retranslateUi

};

namespace Ui {
    class KeyBoardWidget: public Ui_KeyBoardWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_KEYBOARDWIDGET_H
